# Generated by Django 4.2 on 2023-05-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('game', models.SmallIntegerField()),
                ('coltype', models.SmallIntegerField()),
                ('chapter', models.SmallIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture_url', models.CharField(max_length=100)),
            ],
        ),
    ]
