# Generated by Django 4.2 on 2023-05-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinnlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=20)),
                ('query', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
    ]
